#!/bin/bash
mkdir bin
chmod +x *
export MAIN_DIR=$PWD

wget -q "https://download.oracle.com/java/21/archive/jdk-21_linux-x64_bin.tar.gz" -O bin/java.tar.xz
cd $MAIN_DIR/bin
echo "> Extracting Java JDK 21 to the bin/ folder. [THIS MAY TAKE SOME TIME]"
tar -xf java.tar.xz && mv "jdk-21" java_bins